# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Marcel Artz' Website
tagline:          Projects about Scripting, IT-Security, Python, Dark Themes and more!
description:      "Documentation about my personal projects"
url:              https://marcel-artz.de
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Marcel Artz
  url:            https://marcel-artz.de

paginate:         4
paginate_path:    /posts/page:num

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from

# Custom vars
version:            0.1.0

github:
  repo:             https://github.com/ma744/
